### ISSUE TITLE
need more help

### ISSUE THREAD

**Issue by getiany** [sanjayksau/lrmml#1]
I am wondering if you could kindly send me the source program,dataset and the necessary information about it. I promise they will be used only for research purposed.

**Comment by sanjayksau** [comment]
You can reach out at sanjayksau@gmail.com with your university affiliated email id. I can provide source code related details. For datasets etc, you can download from any multi-label dataset repository like Mulan or KDIS.

**Comment by getiany** [comment]
I sent you an email this morning. The email number is 605408063@qq.com,I haven't registered another email yet，

**Comment by getiany** [comment]
Thank you.

**Comment by getiany** [comment]
I can send you my tutor's email. Can you send me the details? His email is 15856517805@163.com， you can call him to confirm that he is president Wang of Anqing Normal University

**Comment by sanjayksau** [comment]
This repo has a working example. If you find it useful please cite the associated paper in your work.
https://github.com/sanjayksau/lrmml-2

**Comment by getiany** [comment]
Thank you very much ,I was just having a meeting with my mentor，so I replied to you a little late.
could you give me the all dataset ?Thank you

**Comment by sanjayksau** [comment]
https://github.com/KKimura360/MLC_toolbox/tree/master/dataset/matfile

**Comment by getiany** [comment]
thank you , thank you , thank you very much.

**Comment by getiany** [comment]
I will cite the associated paper in my work.

**Comment by getiany** [comment]
philosophy  stackex-cs  cooking datasets,I didn't find them in the data set you sent me last time. Can you send me these three data sets again? I'm studying in combination with your code and thesis. If there is anything I don't understand, can I ask you again? Thank you very much for your help.

**Comment by getiany** [comment]
Can you sent the MLLCRS code to me ? My comparison algorithm is not enough.

**Comment by getiany** [comment]
Dear author：
       Thank you for reading!
       I am a one-year graduate student at AnQing University, China.My research is focused on multi-label learning.
       I have recently read your paper: " Multi-label classification with Missing Labels using Label Correlation and Robust Structural Learning".The work was so interesting and it was attractive to me.I am wondering if you could kindly send me the source program,dataset and the necessary information about it. I promise they will be used only for research purposed.
Thank you very much for your kind consideration and I am looking forward to your early reply.
All the best.
Ge WenXin

**Comment by getiany** [comment]
I have read your paper and code and made some innovations, but I still can't compare with your paper. I can't find your code and data set in CodeOcean, so I want to trouble you. I hope you can send me the MLLCRS code so that I can continue to learn from your team. Thank you very much for your constant help

**Comment by sanjayksau** [comment]
> Dear author： Thank you for reading! I am a one-year graduate student at AnQing University, China.My research is focused on multi-label learning. I have recently read your paper: " Multi-label classification with Missing Labels using Label Correlation and Robust Structural Learning".The work was so interesting and it was attractive to me.I am wondering if you could kindly send me the source program,dataset and the necessary information about it. I promise they will be used only for research purposed. Thank you very much for your kind consideration and I am looking forward to your early reply. All the best. Ge WenXin

**Comment by sanjayksau** [comment]
> Dear author： Thank you for reading! I am a one-year graduate student at AnQing University, China.My research is focused on multi-label learning. I have recently read your paper: " Multi-label classification with Missing Labels using Label Correlation and Robust Structural Learning".The work was so interesting and it was attractive to me.I am wondering if you could kindly send me the source program,dataset and the necessary information about it. I promise they will be used only for research purposed. Thank you very much for your kind consideration and I am looking forward to your early reply. All the best. Ge WenXin


MLLCRS is not my paper. Please reach out to the authors of that paper for your request.

**Comment by getiany** [comment]
thank you
